# Generated by Django 2.1.2 on 2018-11-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_group_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_blog_collect_relation',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='user_blog_collect_relation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_group_relation',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user_group_relation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='user_blog_collect_relation',
            unique_together={('blog', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='user_group_relation',
            unique_together={('group', 'user')},
        ),
    ]
