# Generated by Django 2.1.2 on 2018-11-28 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20181128_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_blog_collect_relation',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_date',
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
