# Generated by Django 2.1.2 on 2018-12-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20181214_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', '管理员'), ('c', '创建者'), ('m', '参与者')], default='c', max_length=1)),
            ],
            options={
                'db_table': 'TUJR',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'T',
            },
        ),
        migrations.RenameModel(
            old_name='User_Blog_Collect_Relation',
            new_name='Collection',
        ),
        migrations.AlterUniqueTogether(
            name='user_group_relation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user_group_relation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user_group_relation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='collection',
            table='UBCR',
        ),
        migrations.AlterModelTable(
            name='user',
            table='U',
        ),
        migrations.DeleteModel(
            name='Group_User',
        ),
        migrations.DeleteModel(
            name='User_Group_Relation',
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(through='model.Join', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='join',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Team'),
        ),
        migrations.AddField(
            model_name='join',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
