# Generated by Django 2.1.2 on 2018-12-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20181214_0027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('blog', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('team', 'user')},
        ),
    ]
